name: cavestory
version: '2.6.2-snap0'
summary: Doukutsu Monogatari - Jump-and-run platformer
description: |
  NXEngine Evo is a complete open-source clone/rewrite of the masterpiece
  jump-and-run platformer Doukutsu Monogatari (also known as Cave Story).
  NXEngine Evo [1] is an upgraded/refactored version of NXEngine by Caitlin Shaw [2].
  [1] https://github.com/nxengine/nxengine-evo
  [2] http://nxengine.sourceforge.net/

grade: devel
confinement: strict

apps:
  cavestory:
    command: bash -c "cd $SNAP/bin && $SNAP/bin/desktop-launch $SNAP/bin/nx"
    plugs:
    - opengl
    - unity7
    - wayland
    - x11
    - desktop
    - pulseaudio
    - joystick # FIXME: Joystick doesn't work (yet)
    - process-control # FIXME: Required to make audio work

parts:
  cavestory:
    plugin: nil
    source: https://www.cavestory.org/downloads/cavestoryen.zip
  nxengine-evo:
    plugin: cmake
    source: https://github.com/nxengine/nxengine-evo/archive/v2.6.2.tar.gz
    build-packages:
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libpng-dev
    stage-packages:
      - libgl1-mesa-glx
      - libglew1.13
      - libglu1-mesa
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libpulse0
    build: |
      mkdir build && cd build
      cmake -DCMAKE_BUILD_TYPE=Release ..
      make
      cd ../
      cp -r bin/ $SNAPCRAFT_PART_INSTALL/
    install: |
      # Extract and install data
      cp ../../cavestory/src/CaveStory/Doukutsu.exe .
      ./bin/extract
      cp -r ../../cavestory/src/CaveStory/data/* data
      cp -r data/ $SNAPCRAFT_PART_INSTALL/bin
    after:
      - cavestory
      - desktop-glib-only
